source:      .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
include:     ['.htaccess']
exclude:     ['.gitignore','Gemfile','Gemfile.lock','README.md']
keep_files:  ['.git','.svn']
gems:        ['jekyll-paginate']
whitelist:   ['jekyll-pagination']

future:      true
limit_posts: 0
highlighter: pygments

permalink:     pretty
paginate_path: 'blog/:num'

markdown:      redcarpet
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "<!--more-->"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
url:         https://arcanis.me
enforce_ssl: arcanis.me
lsi:         false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
  fenced_code_blocks: true

rdiscount:
  extensions: []

redcarpet:
  extensions: ["tables", "autolink", "no_intra_emphasis"]

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true
