exclude:       ['.gitignore','Gemfile','Gemfile.lock','README.md','TODO']
permalink:     pretty
paginate:      10
paginate_path: 'blog/:num'
markdown:      rdiscount
baseurl:       /
lsi:           false
